### PR TITLE
Adding admin contact information

### PR DESCRIPTION
**Pull request by james-gibson**

### CODE REVIEW

**Comment by danhannigan** [comment]
I'm fine with merging this but just want to get a thumbs up from @DrewDahlman, @kylecoberly, and @mikemcguire since it's got your info on it, too.

**Comment by kylecoberly** [comment]
+1 for me!

**Comment by kylecoberly** [comment]
Oops, bad instinct from my utlimate-power times

**Comment by DrewDahlman** [comment]
+1

**Comment by mikemcguire** [comment]
-1 this is not how you run a secret society

**Comment by mikemcguire** [comment]
~~Woah I asked that my private info not be used? What kind of fascist group is this?~~ I AM THE CODE LIZARD

**Pull request merged**
