### PR TITLE
Adding first event

### PR DESCRIPTION
**Pull request by kylecoberly**
Following format from https://github.com/HartfordJS/hartfordjs.com

### CODE REVIEW

**Comment by willklein** [comment]
This looks good. We might change up the metadata when we actually setup the Jekyll, but we can amend this at that time.

**Comment by willklein** [comment]
I also recommend putting the event link in an `event_url` or `event_link` property. The date should lose the formatting and just be `YYYY-MM-DD` and we can format it in Liquid.

**Comment by kylecoberly** [comment]
Changed the format

**Comment by kylecoberly** [comment]
Created a new branch "event-development" that includes these commits. Closing this PR.

**Pull request closed without merging**
