### PR TITLE
Obviosly I'm biased. :)

### PR DESCRIPTION
**Pull request by samusgray**
Do we want to include local education options like Galvanize here?

### CODE REVIEW

**Comment by talon** [comment]
As an advocate of the culture of learning I +1 this.

**Comment by DrewDahlman** [comment]
agreed.

**Comment by danhannigan** [comment]
Totally - there's a little V2 I began thinking of that would include such things. Maybe a readme in the base would be good to bring this up or are pull requests the way to go?

**Comment by talon** [comment]
I like PR as a point of discussion but I'm also cool with a readme :)

**Comment by samusgray** [comment]
Awesome. I'm also a PR / issue fan for discussions.

**Comment by danhannigan** [comment]
Cool, I'll get used to it then :)

**Pull request merged**
